//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScriptInfo {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptInfo() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.ScriptInfo", typeof(ScriptInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ScriptInfoWindow_Title {
            get {
                return ResourceManager.GetString("ScriptInfoWindow_Title", resourceCulture);
            }
        }
        
        public static string ScriptInfo_Button_Add {
            get {
                return ResourceManager.GetString("ScriptInfo_Button_Add", resourceCulture);
            }
        }
        
        public static string ScriptInfo_Button_Save {
            get {
                return ResourceManager.GetString("ScriptInfo_Button_Save", resourceCulture);
            }
        }
        
        public static string ScriptInfo_Button_Remove_ToolTip {
            get {
                return ResourceManager.GetString("ScriptInfo_Button_Remove_ToolTip", resourceCulture);
            }
        }
        
        public static string ScriptInfo_MsgBox_Add_Title {
            get {
                return ResourceManager.GetString("ScriptInfo_MsgBox_Add_Title", resourceCulture);
            }
        }
        
        public static string ScriptInfo_MsgBox_Add_Body {
            get {
                return ResourceManager.GetString("ScriptInfo_MsgBox_Add_Body", resourceCulture);
            }
        }
        
        public static string ScriptInfo_MsgBox_Conflict_Title {
            get {
                return ResourceManager.GetString("ScriptInfo_MsgBox_Conflict_Title", resourceCulture);
            }
        }
        
        public static string ScriptInfo_MsgBox_Conflict_Body {
            get {
                return ResourceManager.GetString("ScriptInfo_MsgBox_Conflict_Body", resourceCulture);
            }
        }
        
        public static string ScriptInfo_Header_Name {
            get {
                return ResourceManager.GetString("ScriptInfo_Header_Name", resourceCulture);
            }
        }
        
        public static string ScriptInfo_Header_Value {
            get {
                return ResourceManager.GetString("ScriptInfo_Header_Value", resourceCulture);
            }
        }
    }
}
